name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - run: gem install jekyll

      - run: npm install -g fsh-sushi

      - run: ./gradlew test

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ig/output
